base/Command.js, utils/logger.js
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/androz2091/atlantabot/issues).
=> Apply fixes from CodeFactor

config.sample.js
=> config.sample.js

commands/Administration/goodbye.js, commands/Administration/welcome.js
Ignore arg "test" if plugin welcome or goodbye is not enabled.
Before: the success message is send if the plugin is not enabled
=> Corrige test command welcome and goodbye

package.json
=> Fix version (error npm)

commands/Administration/slowmode.js
fix bug --> https://github.com/Androz2091/AtlantaBot/projects/3#card-24798237
=> fix(slowmode) change time if channel exist

languages/english.js
=> Fix(language) error translate setlang

utils/fortniteShop.js
=> Fix error FNBR api

languages/english.js
**Error un english.js**
**Status:**
=> Fix(translate) fortnite

commands/Economy/work.js
**Fix error pay award**
**Status:**
=> Fix(work) pay award

commands/General/calc.js
**Allow ÷ to calc command**
**Status:**
=> Fix(calc) Allow ÷

commands/Fun/fml.js, docs/commands.md, languages/english.js, languages/french.js
**Add a FML command who displays a random post of viedemerde.fr (french) or fmylife.com (english)**
**Status:**
=> Add FML command

languages/french.js
**Add Ban Title logs translate**
**Status:**
=> Add Ban Title logs translate

commands/Moderation/clear.js
**Ignore pinned messages in clear command**
**Status:**
=> Update(clear.js) Do not delete pinned messages

commands/Moderation/kick.js
**fix the command kick is not responding & remove Cyclic dependency error**
**Status:**
=> Fix(kick.js) error resolveMember

commands/Moderation/mute.js
**Update(mute.js) change .name -> .id (save the ID of the channel)**
**Status:**
=> Update(mute.js) change .name -> .id

commands/Moderation/warn.js, languages/english.js, languages/french.js
**FIx errors in command warn**
**Status:**
=> FIx errors in command warn (not send log & title undefined)

languages/english.js, languages/french.js
**Update donators list and add synaro in GOD**
**Status:**
=> Update donators list

commands/Fun/number.js
**error in guildID (schem mongoose) in number command**
**Status:**
=> fix(number.js) no money win

config.sample.js
**Add link to statuts emojis**
**Status:**
=> Add link to statuts emojis

commands/General/help.js
**Fix error undefined custom command**
**Status:**
=> Fix(help) error undefined custom command

commands/Economy/deposit.js
**Add deposit all command and dep aliase**
**Status:**
=> Update(deposit) add arg "all"

commands/General/help.js, config.sample.js
**Change the way to display emojis in help command (category)**
**Status:**
=> Change the way to display emojis in help command

commands/General/help.js
**Add permissions field in help command**
**Status:**
=> Update(help) Add permissions field

commands/Economy/deposit.js, commands/Economy/withdraw.js, languages/english.js, languages/french.js
**
- Add no money values for withdraw and deposit 
- Add withdraw all command
**
**Status:**
=> Add no money values for withdraw and deposit

utils/fortniteShop.js
**fix(fortniteShop) error display if too long**
**Status:**
=> fix(fortniteShop) error display if too long

languages/english.js, languages/french.js
**Display hours and minutes to 00h00 format**
**Status:**
=> Update printDate function

commands/Administration/addcommand.js
**Fix line break in addcommand**
**Status:**
=> Fix(addcommand) remove line break

docs/installation/linux.md, docs/installation/windows.md
=> Updated Emojis Server URL

languages/english.js
**bug report in discord**
**Status:**
=> Fix(english.js) translate error

commands/Fun/fml.js
**Display credits in a single line**
**Status:**
=> Update(fml.js) display credit in one line

base/Guild.js, commands/Administration/configuration.js, commands/Administration/setreports.js, commands/General/report.js, commands/Owner/getconf.js, languages/english.js, languages/french.js
> I have made an ***setreport {#channel / id}** command and a ***report {@user} {reason}** from the suggestion from `mouton1234#3895`:
**Status:**
=> Report Command

helpers/checkUnmutes.js
A significantly minor change. This line simply checks if the membersData file exists; if not, it simply stops running through the code until the next loop. This will allow people who run the bot themselves to utilize their own Mongo database for muted users.
**Status:**
=> Minor: Add members data check to checkUnmutes.js

languages/english.js
=> Fix: Goodbye test language

commands/Moderation/sanctions.js
Adding x3 aliases (infractions, see-infractions, view-infractions)
**Status:**
=> Add aliases to sanctions command

commands/Fun/lovecalc.js
=> Add lc alias to lovecalc command

commands/Economy/leaderboard.js
=> Add linebreak before sending leaderboard

commands/Owner/servers-list.js
missing cache property in `this.client.guilds.sort()`
**Status:**
=> Add missing cache property

commands/Music/skip.js
replace songs by tracks
**Status:**
=> fix songName in react embed

commands/Music/stop.js
Because bots can't react for skip song if has many bot in channel
**Status:**
=> Use filter user bot insteadof filter client id

base/Atlanta.js, commands/Economy/work.js, commands/General/help.js, commands/General/invitations.js, commands/General/report.js, commands/General/serverinfo.js, commands/General/staff.js, commands/General/stats.js, commands/General/suggest.js, commands/General/userinfo.js, commands/Moderation/poll.js, commands/Music/queue.js, helpers/extenders.js, package.json
=> Général fix

dashboard/views/selector.ejs
Fixation du footer
**Status:**
=> Fix dashboard footer

README.md
Update the Number of Discord Users and the Number of Servers the Bot is in
**Status:**
=> Update user and server count

languages/fr-FR/economy/rob.json
=> Error missing a } at the prefix

commands/General/userinfo.js
Modification of the thumbnail.
If a person has an animated avatar it will now be displayed !
=> ✔ Gif Avatar

README.md
=> Update servers count

commands/Moderation/ban.js
Fixing dm message when you ban people :D
=> Fix DM message when someone is banned

commands/General/hastebin.js
fixed api url issue for hastebin
**Status:**
=> :bug: Change hastebin api url

base/Atlanta.js
=> :art: Refactor discord.js imports

commands/Images/avatar.js
https://discord.js.org/#/docs/main/stable/typedef/ImageURLOptions
=> ⚡️ Use format option for avatar command

base/Atlanta.js
Because in the footer embed type 10 not 20
**Status:**
=> Edit music 🎶

commands/Administration/setfortniteshop.js, commands/Economy/money.js, commands/Economy/profile.js, commands/Economy/work.js, commands/General/fortniteshop.js, commands/General/github.js, commands/General/help.js, commands/General/quote.js, commands/General/report.js, commands/General/someone.js, commands/General/suggest.js, commands/General/translate.js, commands/General/userinfo.js, commands/Moderation/sanctions.js, commands/Owner/servers-list.js
=> Use dynamic option for user avatars

base/Atlanta.js
=> :sparkles: Specified proper intents to fix play command

commands/General/help.js
**Commands are listed inside conf and not just on root so you need to loop/filter inside the conf..**
**Status:**
=> :bug: Fix help command

commands/Owner/servers-list.js
**Status:**
- [ Yes] Code changes have been tested
- [ Yes] Code changes work without errors
=> fix msg.edit({ embeds: [embed]});

dashboard/auth/CheckAuth.js
=> :zap: Clean up check auth

README.md, commands/General/help.js, commands/General/stats.js, docs/faq.md, docs/installation/linux.md, docs/installation/windows.md, emojis.json, scripts/verify-config.js
Fixing the emoji URLs
**Status:**
=> Fix emoji server links

dashboard/routes/discord.js
This (id) needs to be inside an object! Otherwise it will create double entries and even sometimes throw errors when using dashboard!
**Status:**
**Content of the pull request:**  
- Not really a visual change, but fix code in dashboard...
=> 🐛Fix double and wrong entries in Users schema
